= Лабораторна робота №2

== Класи, об’єкти. Масиви. Модифікатори доступу

=== Класи в Java
Класи Java можуть мати методи і атрибути.

* Методи визначають, що клас може зробити.
* Атрибути – це характеристики класу

У Java прийнято, що атрибути класу, які можуть змінюватись, оголошуються з модифікатором доступу `*private*`, що не дозволяє їхнє використання «в обхід» спеціальних методів класу «гетерів» та «сетерів». Своєю чергою, такі методи оголошуються з модифікатором `*public*`, що дозволить їхнє використання з методів інших класів.

Одним з методів класу, що використовується досить часто, є метод `*equals()*`. Цей метод дозволяє перевіряти об’єкти на рівність.

Слід зауважити, що проста перевірка об’єктів на рівність за допомогою операції == дає можливість перевірити лише той факт, що ми маємо справу з посиланнями на один і той самий об’єкт.


**Приклад 1. _Описання класу (у файлі Cat.java)_ **

[source,java]
----
package lab2.cats;

import java.util.Objects;

public class Cat {
    private int idPassport;
    private String name;
    private String breed;
    private char gender;
    private int age;

    public Cat(int idPassport, String name, String breed, char gender, int age) {
        this.idPassport = idPassport;
        this.name = name;
        this.breed = breed;
        this.gender = gender;
        this.age = age;
    }

    public int getIdPassport() {
        return idPassport;
    }

    public void setIdPassport(int idPassport) {
        this.idPassport = idPassport;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBreed() {
        return breed;
    }

    public void setBreed(String breed) {
        this.breed = breed;
    }

    public char getGender() {
        return gender;
    }

    public void setGender(char gender) {
        this.gender = gender;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    @Override
    public String toString() {
        return "Cat{" +
                "idPassport=" + idPassport +
                ", name='" + name + '\'' +
                ", breed='" + breed + '\'' +
                ", gender=" + gender +
                ", age=" + age +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Cat cat = (Cat) o;
        return idPassport == cat.idPassport &&
                gender == cat.gender &&
                age == cat.age &&
                Objects.equals(name, cat.name) &&
                Objects.equals(breed, cat.breed);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idPassport, name, breed, gender, age);
    }
}
----

_**Використання масивів **_

Типи масиву використовуються для визначення масивів – упорядкованих наборів однотипних змінних. Ви можете визначити масив над будь-яким типом, що існує у мові, включно з типами, визначеними користувачем. Крім того, можна користатися масивами масивів чи багатовимірними масивами. Коротко говорячи, якщо ми можемо створити змінну деякого типу, виходить, ми можемо створити й масив змінних цього типу. Разом з тим створення масивів у мові Java може показатися вам незвичним, тому що воно вимагає застосування оператора `*new*`.

**Приклад 2. _Описання масивів і виділення пам'яті для масивів_ **

[source,java]
----
int[] myIntArray;        // описання масиву цілих чисел
myIntArray = new int[8]; // створення масиву з 8 цілих чисел
MyType[] myObjectArray;  // описання масиву об’єктів типу MyType
myObjectArray = new MyType[5];// створення масиву з 5 елементів типу MyType
----

Оператор `*new*` дає команду оболонці часу виконання виділити необхідну кількість пам'яті під масив. Як видно із цього прикладу, не треба повідомляти розмір масиву тоді ж, коли ви створюєте змінну-масив. Після того як ви створили масив оператором `*new*`, доступ до цього масиву здійснюється точно так само, як у мовах С/C++ чи Kotlin.

**Приклад 3. _Присвоювання значень елементам масивів_**
[source,java]
----
myIntArray[0] = 0;
myIntArray[1] = 1;
myIntArray[2] = 2;
myObjectArray[0] = new MyType();
myObjectArray[1] = new MyType();
myObjectArray[2] = new MyType();
myObjectArray[0].setValue(0);
myObjectArray[1].setValue(1);
myObjectArray[2].setValue(2);
----

Масиви в мові Java мають три важливі переваги перед масивами в інших мовах.  По-перше, програмісту не треба вказувати розмір масиву при його оголошенні.  По-друге, будь-який масив у мові Java є змінною — а це значить, що його можна передати як параметр методу й використовувати як значення, що повертається методом. І по-третє, завжди легко довідатися, який розмір даного масиву. Наприклад, так визначається розмір масиву, що був оголошений вище.

*Приклад 4. _Отримання довжини масиву_*

[source,java]
----
int len = myIntArray.length;
System.out.println("Length of myIntArray=" + len);
----

Багатовимірні масиви в мові Java визначаються, як “масиви, елементами яких є масиви”. Тобто двовимірний масив – це масив, елементами якого є лінійні масиви. Наприклад, так відбувається робота з двовимірним масивом

*Приклад 5. _Описання та робота з двовимірним масивом_*

[source,java]
----
double[][] m;
m = new double[3][4]; // масив з трьох рядків, у кожному по 4 елементи
m[1][3] = 5.4; // присвоювання значення елементу, що знаходиться у першому рядку під номером 3
double[][] z;
z = new double[3][];  // массив з трьох рядків
z[0] = new double[1]; // у першому рядку – один елемент
z[1] = new double[2]; // у другому рядку – два
z[2] = new double[3]; // у третьому – три
z[2][2] = 1.5; // припустиме присвоювання
z[0][1] = 5.3; // ПОМИЛКА! У першому рядку є лише один елемент і з індексом 0
----
<<<

*Приклад 6. _Опис головного класу програми, що використовує клас_ `Cat.java` – _у файлі_ `Main.java`*

[source,java]
----
package lab2.demo;

import lab2.cats.Cat;

public class Main {

    public static void main(String[] args) {
       new Main().run();
    }

    private void run() {
        Cat[] cats = fillCatsArray();
        System.out.println("---------------------");
        printCats(cats);
        System.out.println("---------------------");
        printDvorCats(cats);
    }

    private void printDvorCats(Cat[] cats) {
        for (int i = 0; i < cats.length; i++) {
            if (cats[i].getBreed().equals("Dvor")) {
                System.out.println(cats[i]);
            }
        }
    }

    private void printCats(Cat[] cats) {
        for (int i = 0; i < cats.length; i++) {
            System.out.println(cats[i]);
        }
    }

    private Cat[] fillCatsArray() {
        return new Cat[]{
                new Cat(1,"Murka", "Sphinx", 'f', 1),
                new Cat(2, "Matroskin", "Dvor", 'm', 3),
                new Cat(3, "Felix", "Sibir", 'm', 2),
                new Cat(4, "Tom", "Dvor", 'm', 2)
        };
    }

}
----

Коди цього прикладу можна побачити в пакеті "cats" проєкту, що можна знайти за посиланням https://github.com/kafedra-iust/lab2oop.git[]

=== Завдання

.	Створити проєкт, що складається з двох класів: основного (Main) та класу для представлення об’єкта відповідно специфікації, що наведена нижче. Кожний клас повинен бути розміщений у окремому пакеті. У створеному класі визначити приватні поля для зберігання указаних даних, конструктори для створення об’єктів та відкриті методи `setValue()`, `getValue()`, `toString()` для доступу до полів об'єкта.
.	В основному класі програми визначити методи, що створюють масив об'єктів. Задати критерії вибору даних та вивести ці дані на консоль. Для кожного критерію створити окремий метод.
.	Виконати програму та пересвідчитись, що дані зберігаються та коректно виводяться на екран відповідно до вказаних критеріїв.

=== Варіанти завдань

==== Варіант 1

*Student*: id, Прізвище, Ім'я, По батькові, Дата народження, Адреса, Телефон, Факультет, Курс, Група. +
_Скласти масив об'єктів._ +
_Вивести:_

.. Список студентів заданого факультету;
.. Список студентів, які народились після заданого року;
.. Список навчальної групи.

==== Варіант 2
*Customer*: id, Прізвище, Ім'я, По батькові, Адреса, Номер кредитної картки, Баланс рахунку — кількість грошей на ньому (може бути як додатнім, так і від'ємним). +
_Скласти масив об'єктів. +
Вивести:_

.. Список покупців, із указаним іменем;
.. Список покупців, у яких номер кредитної картки знаходиться в заданому інтервалі;
.. Кількість та список покупців,  які мають заборгованість (від’ємний баланс на карті)

==== Варіант 3
*Patient*: id, Прізвище, Ім'я, По батькові, Адреса, Телефон, Номер медичної карти, Діагноз. +
__Скласти масив об'єктів. +
Вивести:__

.. Список пацієнтів, які мають указаний діагноз;
.. Список пацієнтів, номер медичної карти у яких знаходиться в заданому інтервалі;
.. Кількість та список пацієнтів, номер телефона яких починається з указаної цифри


==== Варіант 4
*Abiturient*: id, Прізвище, Ім'я, По батькові, Адреса, Телефон, Середній бал. +
_Скласти масив об'єктів. +
Вивести:_

.. Список абітурієнтів із указаним іменем;
.. Список абітурієнтів, середній бал у яких вище заданого;
.. Вибрати задане число n абітурієнтів, що мають найвищий середній бал.

==== Варіант 5
*Book*: id, Назва, Автор, Видавництво, Рік видання, Кількість сторінок, Ціна. +
_Скласти масив об'єктів. +
Вивести:_

.. Список книг заданого автора;
.. Список книг, що видані заданим видавництвом;
.. Список книг, що випущені після заданого року.

==== Варіант 6
*House*: id, Номер квартири, Площа, Поверх, Кількість кімнат, Вулиця. +
_Скласти масив об'єктів. +
Вивести:_

.. Список квартир, які мають задане число кімнат;
.. Список квартир, які мають задане число кімнат та розташовані на поверсі, який знаходиться в заданому проміжку;
.. Список квартир, які мають площу, що перевищує задану.

==== Варіант 7
*Phone*: id, Прізвище, Ім'я, По батькові, Номер рахунку, Час міських розмов, Час міжміських розмов. +
_Скласти масив об'єктів. +
Вивести:_

.. Відомості про абонентів, у яких час міських розмов перевищує заданий;
.. Відомості про абонентів, які користувались міжміським зв'язком;
.. Відомості про абонентів, чий номер рахунку знаходиться у вказаному діапазоні.

==== Варіант 8
*Car*: id, Модель, Рік випуску, Ціна, Реєстраційний номер. +
_Скласти масив об'єктів. +
Вивести:_

.. Список автомобілів заданої моделі;
.. Список автомобілів заданої моделі, які експлуатуються більше n років;
.. Список автомобілів заданого року випуску, ціна яких більше вказаної.

==== Варіант 9
*Product*: id, Найменування, Виробник, Ціна, Термін зберігання, Кількість. +
_Скласти масив об'єктів. +
Вивести:_

.. Список товарів для заданого найменування;
.. Список товарів для заданого найменування, ціна яких не перевищує задану;
.. Список товарів, термін зберігання яких більше заданого.

==== Варіант 10
*Train*: id, Пункт призначення, Номер поїзда, Час відправлення, Число місць (загальних, купе, плацкарт, люкс). +
_Скласти масив об'єктів. +
Вивести:_

.. Список поїздів, які прямують до заданого пункту призначення;
.. Список поїздів, які прямують до заданого пункту призначення та відправляються після заданої години;
.. Список поїздів, які відправляються до заданого пункту призначення та мають загальні місця.

